services:
      
  db:
    image: postgres:${DB_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_DBNAME:-dbmovie}
      POSTGRES_USER: ${DB_USER:-movie}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./scripts/db:/mnt

  gui:
    image: elestio/pgadmin:${GUI_TAG:-latest}
    restart: unless-stopped
    ports:
      - ${GUI_PORT:-80}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${GUI_USER:-admin@example.org}
      PGADMIN_DEFAULT_PASSWORD: ${GUI_PASSWORD:-password}
    volumes:
      - ./scripts/gui:/var/lib/pgadmin/storage


